import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, CheckCheck, MessageSquarePlus, ShieldAlert } from "lucide-react";
import { apiJson } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

type Notification = { id: string; type: string; title: string; message: string; read: boolean; createdAt: string };

export default function NotificationsPage() {
  const client = useQueryClient(); const { toast } = useToast();
  const [category,setCategory]=useState("idea"); const [message,setMessage]=useState("");
  const { data: notifications=[] } = useQuery<Notification[]>({queryKey:["/api/notifications"],queryFn:()=>apiJson("/api/notifications")});
  const markRead=useMutation({mutationFn:(id:string)=>apiJson(`/api/notifications/${id}/read`,{method:"POST"}),onSuccess:()=>client.invalidateQueries({queryKey:["/api/notifications"]})});
  const feedback=useMutation({mutationFn:()=>apiJson("/api/beta/feedback",{method:"POST",body:JSON.stringify({category,message,page:location.pathname})}),onSuccess:()=>{setMessage("");toast({title:"Feedback sent",description:"It is now in the owner dashboard for review."})}});
  return <div className="max-w-5xl mx-auto px-5 md:px-10 py-8 pb-24 text-white"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-blue-500/15 text-blue-300 grid place-items-center"><Bell/></div><div><h1 className="text-2xl font-black">Updates and help</h1><p className="text-xs text-slate-500 mt-1">Safety messages, order updates, and a direct line to the beta team.</p></div></div>
    <div className="grid lg:grid-cols-[1fr_360px] gap-6 mt-7"><section className="rounded-3xl border border-slate-800 bg-[#111827] p-5"><h2 className="text-sm font-black">Your updates</h2><div className="mt-4 space-y-3">{notifications.length===0?<div className="py-14 text-center text-sm text-slate-500">You’re all caught up.</div>:notifications.map(n=><article key={n.id} className={`rounded-2xl border p-4 ${n.read?"border-slate-800 bg-slate-950/30":"border-blue-400/25 bg-blue-500/10"}`}><div className="flex justify-between gap-3"><div className="flex gap-3">{n.type==="safety"?<ShieldAlert className="text-amber-300" size={18}/>:<Bell className="text-blue-300" size={18}/>}<div><h3 className="text-xs font-black">{n.title}</h3><p className="text-[11px] text-slate-400 mt-1">{n.message}</p><time className="text-[9px] text-slate-600 mt-2 block">{new Date(n.createdAt).toLocaleString()}</time></div></div>{!n.read&&<button aria-label={`Mark ${n.title} read`} onClick={()=>markRead.mutate(n.id)} className="text-blue-300"><CheckCheck size={17}/></button>}</div></article>)}</div></section>
      <aside className="rounded-3xl border border-violet-400/20 bg-violet-500/5 p-5 h-fit"><div className="flex items-center gap-2"><MessageSquarePlus className="text-violet-300" size={18}/><h2 className="text-sm font-black">Tell us what you found</h2></div><p className="text-[11px] text-slate-400 mt-2">During the paper beta, send bugs, confusing moments, or ideas.</p><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-4 w-full h-10 rounded-xl bg-slate-950 border border-slate-700 px-3 text-xs"><option value="idea">I have an idea</option><option value="bug">Something broke</option><option value="confusing">Something was confusing</option><option value="other">Something else</option></select><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="What happened?" className="mt-3 w-full min-h-32 rounded-xl bg-slate-950 border border-slate-700 p-3 text-xs"/><button onClick={()=>feedback.mutate()} disabled={message.trim().length<5||feedback.isPending} className="mt-3 w-full h-10 rounded-xl bg-violet-500 disabled:opacity-40 text-xs font-black">Send feedback</button></aside></div></div>;
}
